### ISSUE TITLE
create readme and explain what this project is about

### ISSUE THREAD

**Issue by martenson** [RECETOX/recetox-aplcms-archive#12]
+ link to other pieces of the workflow

**Comment by hechth** [comment]
This issue overlaps with #6, to create a vignette for this package.

**Comment by martenson** [comment]
I added a basic readme [here](https://github.com/RECETOX/recetox-aplcms/commit/976448deed2d92509ade073dcf7700c5f6abba53).

I assume eventually we will put things together in a documentation outside of the atomic repositories so I will close this issue.
