### ISSUE TITLE
modify aplcms to output apache parquet

### ISSUE THREAD

**Issue by martenson** [RECETOX/recetox-aplcms-archive#13]
The current hd5 format has been shown to not be a good fit for large MS datasets.

This could probably also be implemented at the wrapper level xref: https://github.com/RECETOX/galaxytools/issues/111

**Comment by hechth** [comment]
In order to keep the pure library as clean as possible, I'd suggest putting the IO-related code into the Galaxy wrapper as described in [RECETOX/galaxytools#111](https://github.com/RECETOX/galaxytools/issues/111). This will also maintain compatibility with the upstream repository.
