### ISSUE TITLE
Ensure the tool also works with all formats compatible with mzR

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-aplcms-archive#185]
mzR support mzXML and mzdata formats - it would be nice to also implement the package to natively be able to deal with those formats.

This should be implemented in this function: https://github.com/RECETOX/recetox-aplcms/blob/master/R/load.lcms.R

This should actually first be tested with which formats it already works using this file (https://github.com/RECETOX/recetox-aplcms/blob/master/tests/testdata/mbr_test0_copy.mzml) and converting it to mzXML and mzData formats using proteowizard (msconvert in galaxy).

**Comment by wverastegui** [comment]
The function load.lcms.R supports mzXML format. However, it could not be tested with mzData format since msconvert does not offer conversion to mzData.

**Comment by hechth** [comment]
This should be implemented as a unit test within the package using the mzXML and mzData files.

**Comment by hechth** [comment]
For testing with mzdata you can use the file available here and add it to the remote-files text files which contain the URLs.

https://gitlab.ics.muni.cz/umsa/umsa-files/-/blob/master/testdata/recetox-aplcms/input/alg3.mzdata?ref_type=heads
