### ISSUE TITLE
Implement two.step.hybrid method

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-aplcms-archive#23]
The [two.step.hybrid](https://github.com/RECETOX/recetox-aplcms/blob/master/R/two.step.hybrid.R) method having multiple steps of RT correction (intra batch and inter batch) should also be integrated into our version of the tool and also a `two.step.unsupervised` workflow could be useful.

See RECETOX/galaxytools#174 and RECETOX/galaxytools#175

For a description of the background see the [paper](http://www.nature.com/articles/s41598-020-70850-0)

**Comment by hechth** [comment]
@maximskorik this can be closed I think?

**Comment by maximskorik** [comment]
@hechth Yes, forgot to link that to the PR.

**Comment by maximskorik** [comment]
Implemented in #34
