### ISSUE TITLE
Missing arguments documentation

### ISSUE THREAD

**Issue by xtrojak** [RECETOX/recetox-aplcms-archive#26]
There are some undocumented arguments (marked by `TBA`) which need to be filled. This mostly concerns `hybrid` and `unsupervised` functions.

**Comment by hechth** [comment]
Also the documentation on the standard deviations should be improved - it is not immediately clear what they actually mean.

**Comment by hechth** [comment]
Lot's of information can be taken from the initial tutorial: http://web1.sph.emory.edu/apLCMS/frame%201.htm
