### ISSUE TITLE
Extract function for often occurring code snippets code

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-aplcms-archive#65]
@zargham-ahmad wasn't exactly the same code also in adjust.time.R?

_Originally posted by @hechth in https://github.com/RECETOX/recetox-aplcms/pull/63#discussion_r900103997_

**Comment by hechth** [comment]
@xtrojak @zargham-ahmad @maximskorik @wverastegui I think we should have an afternoon session on this in person beore release and go through the whole codebase and identify those patterns and pull them out.

**Comment by xtrojak** [comment]
There is also reoccurring extracted function to compute mass density and its turning points in `feature.align`, `adaptive.bin`, and `recover.weaker`. Such code can be possibly extracted from other functions.

**Comment by hechth** [comment]
- [ ] boundaries
- [ ] peaks & valleys
- [ ] prof.to.features line 627 - 632, 681-685
- [x] init cluster
