### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-aplcms-archive#83]
- [x] Tibble construction/slice in for loop in `adaptive.bin`
- [x] Make comparison of runtime in full dataset test case
- [x] Benchmark performance in unsupervised test case
- [x] Benchmark the performance in 'extract.features' tests
- [ ] Investigate parallel options -> foreach, dopar etc.
- [ ] Parallel dataframe operations -> purrr

**Comment by maximskorik** [comment]
For parallel dataframe operations `furrr` package may be worth checking out. https://furrr.futureverse.org
