### ISSUE TITLE
Simplify feature.align output

### ISSUE THREAD

**Issue by xtrojak** [RECETOX/recetox-aplcms-archive#87]
The `feature.align` function output 4 values: 

- two numbers `mz_tol_relative` and `rt_tol_relative` (which are fine),
- and two tables `aligned.ftrs` and `pk.times` with the following columns:

```
aligned.ftrs - average of m/z, average of rt, min of m/z, max of m/z, the sum of areas per sample
pk.times     - average of m/z, average of rt, min of m/z, max of m/z, the median of rt per sample
```

I think these two tables could be merged and output simplified. However, this is quite a major refactoring step across the whole package.

Further steps:
- [x] #108 
- [x] #123

**Comment by hechth** [comment]
Basically it would be good to split the output into 3 individual tables.

First table is the `variable metadata` table aking to XCMS (see [here](https://umsa.cerit-sc.cz/datasets/c3ef83d0f1c989f7/display?to_ext=tabular)
Second table would be the intensity table (rows are features and columns samples).
Third is the rt table with rows being features and columns the samples.

An example of XCMS is available here: https://umsa.cerit-sc.cz/u/hechth/h/w4m-tutorial

Example:
```
    # variable_metadata_row <- (feature_id, mean_mz, min_mz, max_mz, mean_rt, min_rt, max_rt, num_peaks, sample_presence)
    # intensity_row <- (feature_id, sample_0_intensity, sample_1_intensity, ...)
    # rt_row <- (feature_id, sample_0_rt, sample_1_rt, ...)
```
